config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  # as: - this allows a custom path to be created, so the example would be 'portfolio_show_path(@portfolio_item)'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'anything can go here' - this is the url path.
  # to: 'pages#about' - links the url path to the pages#show action.
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
      get :toggle_featured
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil })
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy]

  layout 'blog'

  def index
    @topics = Topic.all
  end

  def show
    if logged_in?(:site_admin)
      @blogs = @topic.blogs.recent.page(params[:page]).per(5)
    else
      @blogs = @topic.blogs.published.recent.page(params[:page]).per(5)
    end
  end

  def new
    @topic = Topic.new
  end

  def edit; end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy!

    redirect_to topics_path, notice: 'Topic was successfully deleted'
  end

  private

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <% topic.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end%>

app/views/topics/_topic.html.erb
<div>
  <%= link_to topic.title, topic_path(topic) %>
</div>

app/views/topics/edit.html.erb
<div class="col-md-8 blog-main">
  <h1>Editing Topic</h1>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Show', @topic %> |
  <%= link_to 'Back', topics_path %>
</div>

app/views/topics/index.html.erb
<div class="col-sm-8 blog-main">

  <h1> Topics </h1>

  <% if logged_in?(:site_admin) %>
    <%= link_to 'Create New Topic', new_topic_path, class: "btn btn-dark btn-lg" %>

  <% end %>

  <%= render @topics %>

</div>

app/views/topics/new.html.erb
<div class="col-md-8 blog-main">
  <h1>New Topic</h1>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<div class="col-sm-8 blog-main">

  <h1> <%= @topic.title %> </h1>

  <%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>

</div>